version: "3.8"
services:
  ping-client:
    build:
      context: ./client
      args:
        - NODE_ENV=development
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/client/app
      - /home/client/app/node_modules
    restart: on-failure
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/v1
      NEXT_PUBLIC_NETWORK_API_URL: http://ping-api:8080/v1
  ping-api:
    build:
      context: ./api
      args:
        - NODE_ENV=development
    command: sh -c "npm run dev"
    ports:
      - 8080:8080
    volumes:
      - ./api:/home/api/app
      - /home/api/app/node_modules
    restart: on-failure
    depends_on:
      - ping-db
  ping-db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=ping
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./api/db/data/postgres:/var/lib/postgresql
    ports:
      - 5432:5432
