version: "3.8"
services:
  ping-client:
    build: ./client
    command: sh -c "npm install && npm run dev"
    container_name: ping-client
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/app/client
    working_dir: /home/app/client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/v1
      NEXT_PUBLIC_NETWORK_API_URL: http://ping-api:8080/v1
  ping-api:
    platform: linux/x86_64
    command: sh -c "npm install && npm run dev"
    build: ./api
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9240:9240 # Node inspect
    volumes:
      - ./api:/home/app/api
    working_dir: /home/app/api
    restart: on-failure
    depends_on:
      - ping-db
  ping-db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=ping
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./api/db/data/postgres:/var/lib/postgresql
    ports:
      - 5432:5432
